# Generated by Django 2.2 on 2019-04-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='state',
            new_name='thana',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='state',
            new_name='thana',
        ),
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='user_photo'),
        ),
    ]
